version: "3.9"
services:
  bot:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - redis_db
    environment:
      - USE_REDIS=True
      - REDIS_IP=redis_db
      - REDIS_PORT=6379
      - DEBUG=False
      - API_HOST=http://dev.teleagronom.com
      # Set SENTRY_DSN
  redis_db:
    image: redis
