# coding: utf-8

"""
    Teleagronom

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MycologicalCalculatorDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'preceding_culture': 'AllOfMycologicalCalculatorDetailPrecedingCulture',
        'culture': 'AllOfMycologicalCalculatorDetailCulture',
        'name': 'str',
        'creation_date': 'datetime',
        'is_done': 'bool',
        'sampling_coordinates': 'str',
        'probe_number': 'int',
        'cultures_comment': 'str',
        'interpretation': 'dict(str, Object)',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'preceding_culture': 'preceding_culture',
        'culture': 'culture',
        'name': 'name',
        'creation_date': 'creation_date',
        'is_done': 'is_done',
        'sampling_coordinates': 'sampling_coordinates',
        'probe_number': 'probe_number',
        'cultures_comment': 'cultures_comment',
        'interpretation': 'interpretation',
        'user': 'user'
    }

    def __init__(self, id=None, preceding_culture=None, culture=None, name=None, creation_date=None, is_done=None, sampling_coordinates=None, probe_number=None, cultures_comment=None, interpretation=None, user=None):  # noqa: E501
        """MycologicalCalculatorDetail - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._preceding_culture = None
        self._culture = None
        self._name = None
        self._creation_date = None
        self._is_done = None
        self._sampling_coordinates = None
        self._probe_number = None
        self._cultures_comment = None
        self._interpretation = None
        self._user = None
        self.discriminator = None
        self.id = id
        self.preceding_culture = preceding_culture
        self.culture = culture
        self.name = name
        self.creation_date = creation_date
        self.is_done = is_done
        self.sampling_coordinates = sampling_coordinates
        self.probe_number = probe_number
        self.cultures_comment = cultures_comment
        self.interpretation = interpretation
        self.user = user

    @property
    def id(self):
        """Gets the id of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The id of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MycologicalCalculatorDetail.


        :param id: The id of this MycologicalCalculatorDetail.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def preceding_culture(self):
        """Gets the preceding_culture of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The preceding_culture of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: AllOfMycologicalCalculatorDetailPrecedingCulture
        """
        return self._preceding_culture

    @preceding_culture.setter
    def preceding_culture(self, preceding_culture):
        """Sets the preceding_culture of this MycologicalCalculatorDetail.


        :param preceding_culture: The preceding_culture of this MycologicalCalculatorDetail.  # noqa: E501
        :type: AllOfMycologicalCalculatorDetailPrecedingCulture
        """
        if preceding_culture is None:
            raise ValueError("Invalid value for `preceding_culture`, must not be `None`")  # noqa: E501

        self._preceding_culture = preceding_culture

    @property
    def culture(self):
        """Gets the culture of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The culture of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: AllOfMycologicalCalculatorDetailCulture
        """
        return self._culture

    @culture.setter
    def culture(self, culture):
        """Sets the culture of this MycologicalCalculatorDetail.


        :param culture: The culture of this MycologicalCalculatorDetail.  # noqa: E501
        :type: AllOfMycologicalCalculatorDetailCulture
        """
        if culture is None:
            raise ValueError("Invalid value for `culture`, must not be `None`")  # noqa: E501

        self._culture = culture

    @property
    def name(self):
        """Gets the name of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The name of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MycologicalCalculatorDetail.


        :param name: The name of this MycologicalCalculatorDetail.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def creation_date(self):
        """Gets the creation_date of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The creation_date of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this MycologicalCalculatorDetail.


        :param creation_date: The creation_date of this MycologicalCalculatorDetail.  # noqa: E501
        :type: datetime
        """
        if creation_date is None:
            raise ValueError("Invalid value for `creation_date`, must not be `None`")  # noqa: E501

        self._creation_date = creation_date

    @property
    def is_done(self):
        """Gets the is_done of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The is_done of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: bool
        """
        return self._is_done

    @is_done.setter
    def is_done(self, is_done):
        """Sets the is_done of this MycologicalCalculatorDetail.


        :param is_done: The is_done of this MycologicalCalculatorDetail.  # noqa: E501
        :type: bool
        """
        if is_done is None:
            raise ValueError("Invalid value for `is_done`, must not be `None`")  # noqa: E501

        self._is_done = is_done

    @property
    def sampling_coordinates(self):
        """Gets the sampling_coordinates of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The sampling_coordinates of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: str
        """
        return self._sampling_coordinates

    @sampling_coordinates.setter
    def sampling_coordinates(self, sampling_coordinates):
        """Sets the sampling_coordinates of this MycologicalCalculatorDetail.


        :param sampling_coordinates: The sampling_coordinates of this MycologicalCalculatorDetail.  # noqa: E501
        :type: str
        """
        if sampling_coordinates is None:
            raise ValueError("Invalid value for `sampling_coordinates`, must not be `None`")  # noqa: E501

        self._sampling_coordinates = sampling_coordinates

    @property
    def probe_number(self):
        """Gets the probe_number of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The probe_number of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: int
        """
        return self._probe_number

    @probe_number.setter
    def probe_number(self, probe_number):
        """Sets the probe_number of this MycologicalCalculatorDetail.


        :param probe_number: The probe_number of this MycologicalCalculatorDetail.  # noqa: E501
        :type: int
        """
        if probe_number is None:
            raise ValueError("Invalid value for `probe_number`, must not be `None`")  # noqa: E501

        self._probe_number = probe_number

    @property
    def cultures_comment(self):
        """Gets the cultures_comment of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The cultures_comment of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: str
        """
        return self._cultures_comment

    @cultures_comment.setter
    def cultures_comment(self, cultures_comment):
        """Sets the cultures_comment of this MycologicalCalculatorDetail.


        :param cultures_comment: The cultures_comment of this MycologicalCalculatorDetail.  # noqa: E501
        :type: str
        """
        if cultures_comment is None:
            raise ValueError("Invalid value for `cultures_comment`, must not be `None`")  # noqa: E501
        allowed_values = ["cultures_match", "groups_match", "groups_differ"]  # noqa: E501
        if cultures_comment not in allowed_values:
            raise ValueError(
                "Invalid value for `cultures_comment` ({0}), must be one of {1}"  # noqa: E501
                .format(cultures_comment, allowed_values)
            )

        self._cultures_comment = cultures_comment

    @property
    def interpretation(self):
        """Gets the interpretation of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The interpretation of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: dict(str, Object)
        """
        return self._interpretation

    @interpretation.setter
    def interpretation(self, interpretation):
        """Sets the interpretation of this MycologicalCalculatorDetail.


        :param interpretation: The interpretation of this MycologicalCalculatorDetail.  # noqa: E501
        :type: dict(str, Object)
        """
        if interpretation is None:
            raise ValueError("Invalid value for `interpretation`, must not be `None`")  # noqa: E501

        self._interpretation = interpretation

    @property
    def user(self):
        """Gets the user of this MycologicalCalculatorDetail.  # noqa: E501


        :return: The user of this MycologicalCalculatorDetail.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this MycologicalCalculatorDetail.


        :param user: The user of this MycologicalCalculatorDetail.  # noqa: E501
        :type: int
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MycologicalCalculatorDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MycologicalCalculatorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
