# coding: utf-8

"""
    Teleagronom

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlantProtectionProductApplicationToCulture(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'culture': 'PlantProtectionCulture'
    }

    attribute_map = {
        'culture': 'culture'
    }

    def __init__(self, culture=None):  # noqa: E501
        """PlantProtectionProductApplicationToCulture - a model defined in Swagger"""  # noqa: E501
        self._culture = None
        self.discriminator = None
        self.culture = culture

    @property
    def culture(self):
        """Gets the culture of this PlantProtectionProductApplicationToCulture.  # noqa: E501


        :return: The culture of this PlantProtectionProductApplicationToCulture.  # noqa: E501
        :rtype: PlantProtectionCulture
        """
        return self._culture

    @culture.setter
    def culture(self, culture):
        """Sets the culture of this PlantProtectionProductApplicationToCulture.


        :param culture: The culture of this PlantProtectionProductApplicationToCulture.  # noqa: E501
        :type: PlantProtectionCulture
        """
        if culture is None:
            raise ValueError("Invalid value for `culture`, must not be `None`")  # noqa: E501

        self._culture = culture

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlantProtectionProductApplicationToCulture, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlantProtectionProductApplicationToCulture):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
