from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from swagger_client.api.authentication_controller_api import AuthenticationControllerApi
from swagger_client.api.barley_determinant_controller_api import BarleyDeterminantControllerApi
from swagger_client.api.barley_log_controller_api import BarleyLogControllerApi
from swagger_client.api.barley_question_controller_api import BarleyQuestionControllerApi
from swagger_client.api.basic_error_controller_api import BasicErrorControllerApi
from swagger_client.api.carrot_determinant_controller_api import CarrotDeterminantControllerApi
from swagger_client.api.carrot_disease_controller_api import CarrotDiseaseControllerApi
from swagger_client.api.carrot_disease_file_controller_api import CarrotDiseaseFileControllerApi
from swagger_client.api.carrot_log_controller_api import CarrotLogControllerApi
from swagger_client.api.carrot_question_controller_api import CarrotQuestionControllerApi
from swagger_client.api.cereal_disease_controller_api import CerealDiseaseControllerApi
from swagger_client.api.cereal_disease_file_controller_api import CerealDiseaseFileControllerApi
from swagger_client.api.culture_controller_api import CultureControllerApi
from swagger_client.api.disease_controller_api import DiseaseControllerApi
from swagger_client.api.disease_file_controller_api import DiseaseFileControllerApi
from swagger_client.api.fed_calculator_controller_api import FedCalculatorControllerApi
from swagger_client.api.fertilizer_controller_api import FertilizerControllerApi
from swagger_client.api.fertilizer_type_controller_api import FertilizerTypeControllerApi
from swagger_client.api.liquid_calculator_controller_api import LiquidCalculatorControllerApi
from swagger_client.api.pesticide_controller_api import PesticideControllerApi
from swagger_client.api.potato_determinant_controller_api import PotatoDeterminantControllerApi
from swagger_client.api.potato_log_controller_api import PotatoLogControllerApi
from swagger_client.api.potato_question_controller_api import PotatoQuestionControllerApi
from swagger_client.api.region_controller_api import RegionControllerApi
from swagger_client.api.regulatory_calculator_controller_api import RegulatoryCalculatorControllerApi
from swagger_client.api.request_controller_api import RequestControllerApi
from swagger_client.api.review_controller_api import ReviewControllerApi
from swagger_client.api.rye_determinant_controller_api import RyeDeterminantControllerApi
from swagger_client.api.rye_log_controller_api import RyeLogControllerApi
from swagger_client.api.rye_question_controller_api import RyeQuestionControllerApi
from swagger_client.api.settlement_balance_calculator_controller_api import SettlementBalanceCalculatorControllerApi
from swagger_client.api.stand_by_controller_api import StandByControllerApi
from swagger_client.api.task_controller_api import TaskControllerApi
from swagger_client.api.task_file_controller_api import TaskFileControllerApi
from swagger_client.api.user_rest_controller_api import UserRestControllerApi
from swagger_client.api.wheat_determinant_controller_api import WheatDeterminantControllerApi
from swagger_client.api.wheat_log_controller_api import WheatLogControllerApi
from swagger_client.api.wheat_question_controller_api import WheatQuestionControllerApi
